# Generated by Django 3.1.3 on 2020-11-23 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0004_auto_20201123_0023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
