# Generated by Django 3.1.5 on 2021-01-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0008_auto_20210124_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemPage',
        ),
    ]
