# Generated by Django 3.1.5 on 2021-01-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_contentpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standartpage',
            name='author',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
